# fly.toml app configuration file generated for hyperbolic-agentkit-late-feather-7146 on 2025-02-28T09:54:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyperbolic-agentkit-voice'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 10
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[websocket]
  IDLE_TIMEOUT = 300  # 5 minutes in seconds
